-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.city
(
    city_cust character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT city_pkey PRIMARY KEY (city_cust)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id character varying COLLATE pg_catalog."default" NOT NULL,
    customer_unique_id character varying COLLATE pg_catalog."default",
    customer_zip_code_prefix integer,
    customer_city character varying COLLATE pg_catalog."default",
    customer_state character varying COLLATE pg_catalog."default",
    CONSTRAINT customer_pkey PRIMARY KEY (customer_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.geolocation
(
    geolocation_zip_code_prefix integer,
    geolocation_lat numeric,
    geolocation_lng numeric,
    geolocation_city character varying COLLATE pg_catalog."default",
    geolocation_state character varying COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.latitude
(
    latitude numeric NOT NULL,
    CONSTRAINT latitude_pkey PRIMARY KEY (latitude)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.longitude
(
    longitude numeric NOT NULL,
    CONSTRAINT longitude_pkey PRIMARY KEY (longitude)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    order_id character varying COLLATE pg_catalog."default" NOT NULL,
    order_item_id character varying COLLATE pg_catalog."default" NOT NULL,
    product_id character varying COLLATE pg_catalog."default",
    seller_id character varying COLLATE pg_catalog."default",
    shipping_limit_date date,
    price numeric,
    freight_value numeric
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.order_payments
(
    order_id character varying COLLATE pg_catalog."default" NOT NULL,
    payment_sequential integer,
    payment_type character varying COLLATE pg_catalog."default",
    payment_installments integer,
    payment_value numeric
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.order_reviews
(
    review_id character varying COLLATE pg_catalog."default" NOT NULL,
    order_id character varying COLLATE pg_catalog."default",
    review_score integer,
    review_comment_title character varying COLLATE pg_catalog."default",
    review_comment_message character varying COLLATE pg_catalog."default",
    review_creation_date date,
    review_answer_timestamp timestamp without time zone
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id character varying COLLATE pg_catalog."default" NOT NULL,
    customer_id character varying COLLATE pg_catalog."default",
    order_status character varying COLLATE pg_catalog."default",
    order_purchase_timestamp timestamp without time zone,
    order_approved_at timestamp without time zone,
    order_delivered_carrier_date timestamp without time zone,
    order_delivered_customer_date timestamp without time zone,
    order_estimated_delivery_date timestamp without time zone,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_type character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (payment_type)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.product
(
    product_no integer,
    product_id character varying COLLATE pg_catalog."default" NOT NULL,
    product_category_name character varying COLLATE pg_catalog."default",
    product_name_lenght numeric,
    product_description_lenght numeric,
    product_photos_qty numeric,
    product_weight_g numeric,
    product_length_cm numeric,
    product_height_cm numeric,
    product_width_cm numeric,
    CONSTRAINT product_pkey PRIMARY KEY (product_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    review_id character varying COLLATE pg_catalog."default" NOT NULL,
    review_score integer,
    review_comment_title character varying COLLATE pg_catalog."default",
    review_comment_message character varying COLLATE pg_catalog."default",
    review_creation_date date,
    review_answer_timestamp timestamp without time zone,
    CONSTRAINT reviews_pkey PRIMARY KEY (review_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.sellers
(
    seller_id character varying COLLATE pg_catalog."default" NOT NULL,
    seller_zip_code_prefix integer,
    seller_city character varying COLLATE pg_catalog."default",
    seller_state character varying COLLATE pg_catalog."default",
    CONSTRAINT sellers_pkey PRIMARY KEY (seller_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.state_cd
(
    state_cd character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_state PRIMARY KEY (state_cd)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.zip_code
(
    zip_code_prefix integer NOT NULL,
    CONSTRAINT zip_code_pkey PRIMARY KEY (zip_code_prefix)
)
WITH (
    OIDS = FALSE
);



